name: Run Selenium Test

on:
  push:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          java-version: "22"
          cache: maven
          distribution: "temurin"

      # Setup Chrome
      - uses: browser-actions/setup-chrome@latest

      # Run Maven tests and generate Allure results
      - run: mvn clean test

      # Debug: List Allure Results Directory
      - name: List Allure Results Directory
        run: ls -R target/allure-results

      # Install Allure
      - name: Install Allure
        run: |
          brew install allure

      # Generate Allure report
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o allure-report

      # Debug: List Allure Report Directory
      - name: List Allure Report Directory
        run: ls -R allure-report

      # Upload Allure report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Publish Allure Report to GitHub Pages
        if: success() # Only run if the previous steps succeed
        run: |
          git config --global user.email "mohamed_yehia@acu.edu.eg"
          git config --global user.name "MohamedYehia"
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          git rm -rf .
          cp -r allure-report/* .
          git add .
          git commit -m "Publishing Allure Report to GitHub Pages"
          git push --force origin gh-pages
